# Generated by Django 4.2.7 on 2023-11-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_generatedexcelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedexcelfile',
            name='excel_file',
            field=models.FileField(upload_to='data/excel_files/'),
        ),
    ]
