# Generated by Django 4.2.7 on 2023-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_generatedexcelfile_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='graph_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
