name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libcurl4-openssl-dev libpython3-dev libssl-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage coveralls
    - name: Run Tests
      run: coverage run --omit=*/tests/*,*/migrations/* --source=cs130_efi manage.py test
    - name: Coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
