name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      fuseki:
        image: stain/jena-fuseki
        ports:
          - 3030:3030
        options: --env 'ADMIN_PASSWORD=pass' --env 'FUSEKI_DATASET_1=mydataset' --env 'FUSEKI_DB_1=tdb2'

    steps:
      # need checkout before using docker-compose-action
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          test-container: web
          test-command: "python3 manage.py test"
